# Generated by Django 3.2.5 on 2021-07-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=20),
        ),
    ]
