# Generated by Django 3.2.5 on 2021-07-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0003_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='htext',
            field=models.CharField(default='text', max_length=50),
        ),
    ]
