# Generated by Django 3.2.5 on 2021-07-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0005_books_htext'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='Title Here', max_length=50),
        ),
    ]
