# Generated by Django 3.2.5 on 2021-07-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0006_portfolio_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('news_img', models.ImageField(blank=True, upload_to='news/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
