# Generated by Django 3.2.5 on 2021-07-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0007_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
