# Generated by Django 3.2.5 on 2021-07-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0010_auto_20210706_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/'),
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
