# Generated by Django 3.2.5 on 2021-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0011_auto_20210706_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
