# Generated by Django 3.2.5 on 2021-07-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0015_alter_books_htext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='htext',
            field=models.CharField(default='text', max_length=500),
        ),
    ]
