# Generated by Django 3.2.5 on 2021-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0016_alter_books_htext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='htext',
        ),
        migrations.AddField(
            model_name='books',
            name='captain',
            field=models.CharField(default='Captain', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='member1',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='member2',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='member3',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='member4',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='member5',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='member6',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='member7',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='member8',
            field=models.CharField(default='Member', max_length=50),
        ),
    ]
