# Generated by Django 3.2.5 on 2021-07-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0017_auto_20210706_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='captain',
            new_name='htext',
        ),
        migrations.RemoveField(
            model_name='books',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='books',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='books',
            name='member3',
        ),
        migrations.RemoveField(
            model_name='books',
            name='member4',
        ),
        migrations.RemoveField(
            model_name='books',
            name='member5',
        ),
        migrations.RemoveField(
            model_name='books',
            name='member6',
        ),
        migrations.RemoveField(
            model_name='books',
            name='member7',
        ),
        migrations.RemoveField(
            model_name='books',
            name='member8',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='htext',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='captain',
            field=models.CharField(default='Captain', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='member1',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='member2',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='member3',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='member4',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='member5',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='member6',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='member7',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='Team Name', max_length=50),
        ),
    ]
