# Generated by Django 3.2.5 on 2021-07-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0018_auto_20210706_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='member7',
        ),
    ]
