# Generated by Django 3.2.5 on 2021-07-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0020_alter_books_htext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='htext',
            new_name='player',
        ),
    ]
